### ISSUE TITLE
Is the antenna path 50 ohms?

### ISSUE THREAD

**Issue by saffetblt** [hallard/RAK3172-Breakout#1]
Hi Charles, Are you sure the path from the Lora module to the antenna is 50 ohms? When I calculate using the calculation tools, it comes out 60 ohms. Could you please explain about this?

Thank you.

**Comment by hallard** [comment]
Not sure, I did not spent time on this one, because I'm not sure the trace going out RF module (the one without IPEX) to the PAD is 50Ohms matched so in all case if you need precise 50Ohm you should add matching components and I was short in space (and too lazy) to add them.

Anyway you can also use module with IPEX and use IPEX to SMA to see if it's better.
